travis:
  secure:
    BINSTAR_TOKEN: ATT+UdSMqKRdSVuEZ1NoPH3raOg/xMUNCBFgc8oX7Z6CWODJ4ouzFh73O7W91tptwV9wnSemo2fBQHcY8X1QpGvdeC/zX9AwutdcpvItbxiY2W2DDJ3QfGLAVNA/HGC2YWFXCNr5pPFPxvBss0ajSW1kIW2gp3e3x1CkU0C9wrMAGeozpZYgnKmCt5+H9LPkBNip/wDiSaEB6KAOgns8gkpSl0XyhrEsIDYTRr5DM3lAYjOlt7v18AVEU5QJAIf9JzTOdc4yMx3Jv1mD9p6YBoIec9DCNaUjoel1Vd4d2I5H049cuCSSXEqEw+WPerl2r8wrzFPBpBggcCmrVAbBm6TLUBzSOhD7XKUbRohcA6i3TfdgKFT0iaXhqqPInz0jzl9yavj/USbHjZYyQhT2LBO5FxFecBaJuTx205Nw0hNqW6Gc7qxXHrFCaoJ52P9DeNoMVWfwm+6H3DFP0mb8lauCxiUveIgWstbW974r1HcRzD/Y7wLJZPEprd1zhc4vCQR9mUqbz/1bTEw3smESqHQ6Ztox9Fev7iqnbtRBArsdG/Xdi8PWtd3OCsK0SK/dLhH/eF6tsRJnNxwQBiAs7A97VitzBA+1/VkQuhOS7+gImpFOWwqbJNpxMjk4nCV9njAkSLLI470lsK7NMstGPRDFYtxkKsmKbWedVvmimDc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
